### PR TITLE
Add support for bower package manager

### PR DESCRIPTION
**Pull request by peters**
Hi,

Added support for bower package manager.

Visit http://bower.io for installation instructions.

After you have installed bower, you need to register the package:
bower register jquery.breakpoints git://github.com/xoxco/breakpoints.git

### CODE REVIEW

**Comment by Anahkiasen** [comment]
+1 for this

**Comment by peters** [comment]
@xoxco bump

**Comment by deg84** [comment]
+1

**Comment by dan2k3k4** [comment]
Hmm I did not see this, I made a similar PR just now for bower.json to fix the install, this seems better though

**Pull request closed without merging**
